import Head from "next/head";
import styles from "@/styles/Home.module.css";
import MainLayout from "../layouts/MainLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
		  </Head>
		  <MainLayout>
		  <main>
        <div className={styles.center}>
          <h2>Hello!</h2>
          <h1>Here are the greatest hits</h1>
        </div>
      </main>
		  </MainLayout>
    </>
  );
}
